---
Name: commentroutes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    # handle old 2.4 style urls
    'CommentingController//$Action/$ID/$OtherID': 'SilverStripe\Comments\Controllers\CommentingController'
    'PageComments/$Action/$ID/$OtherID': 'SilverStripe\Comments\Controllers\CommentingController'
    'PageComments_Controller/$Action/$ID/$OtherID': 'SilverStripe\Comments\Controllers\CommentingController'
